apiVersion: v1
kind: Service
metadata:
  name: vprocache01
spec:
  ports:
    - port: 11211
      targetPort: 11211 # Changed to a numeric port to match the application's port
      protocol: TCP
  selector:
    app: vprocache01
  type: ClusterIP
