apiVersion: apps/v1
kind: Deployment
metadata:
  name: appmemc
  labels:
    app: appmemc
spec:
  selector:
    matchLabels:
      app: appmemc
  replicas: 1
  template:
    metadata:
      labels:
        app: appmemc
    spec:
      containers:
        - name: appmemc
          image: memcached
          ports:
            - containerPort: 11211
              name: appmemcport
