apiVersion: apps/v1
kind: Deployment
metadata:
  name: apprmq
  labels:
    app: apprmq
spec:
  selector:
    matchLabels:
      app: apprmq  # This should match the label in the template
  replicas: 1
  template:
    metadata:
      labels:
        app: apprmq  # This label should match the selector
    spec:
      containers:
        - name: apprmq
          image: rabbitmq
          ports:
            - containerPort: 15672
              name: rmq-port
          env:
            - name: RABITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  key: rmq-pass
                  name: app-secret
            - name: RABBIT_DEFAULT_USER
              value: "guest"
